#!/bin/sh

IN="$1"

set +eux;
make dict;

echo "Test file:'${IN}'"
IBYTES=`cat "${IN}" | wc | awk '{print $3}'`
OBYTES=`cat "${IN}" | ./dict c | wc | awk '{print $3}'`

echo "IBYTES=${IBYTES} OBYTES=${OBYTES}"
RATIO=`echo "2k ${OBYTES} ${IBYTES} / 100 * p" | dc`
echo "RATIO=${RATIO}%"

